name: Build
permissions:
    contents: write
on:
  push:
    tags:
      - 'v*' 

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      dev: ${{contains(github.ref_name,'dev')}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1000
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
            go-version-file: 'go.mod'
            cache: true
      - name: Install git-chglog
        run: |
          go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest
      - name: Generate Changelog
        run: |
          git-chglog -o RELEASE.md ${{github.ref_name}}
      - name: Update Changelog
        if: ${{!env.dev}}
        run: |
          if ! grep -Fq "[${{github.ref_name}}]" CHANGELOG.md;then
            cat RELEASE.md CHANGELOG.md > CHANGELOG.NEW.md || true
            mv CHANGELOG.NEW.md CHANGELOG.md
            git add CHANGELOG.md
            if ! git diff --cached --quiet;then
              git config user.name "github-actions[bot]"
              git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
              git commit -m "更新 CHANGELOG.md"
              git push origin main
            fi
          fi
      - name: Build ll-killer-go
        run: |
          for arch in amd64 arm64 loong64; do
            GOARCH=$arch make ll-killer
            mv ll-killer ll-killer-$arch
          done
          sha1sum ll-killer-* >ll-killer.sha1sum
          
          XDASH='```'
          cat >> RELEASE.md <<EOF
          ## SHA1哈希值
          $XDASH
          $(cat ll-killer.sha1sum)
          $XDASH
          EOF
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{env.dev}}
          body_path: ./RELEASE.md
          files: |
            ./ll-killer-*
            ./ll-killer.sha1sum
