name: Build
permissions:
    contents: write
on:
  push:
    tags:
      - 'v*' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
            go-version-file: 'go.mod'
            cache: true
      - name: Build ll-killer-go
        run: |
          for arch in amd64 arm64 loong64; do
            GOARCH=$arch make ll-killer
            mv ll-killer ll-killer-$arch
          done
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./ll-killer-*
