name: Build
permissions:
  contents: write
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      release: ${{ contains(github.ref,'refs/tags/') && startsWith(github.ref_name,'v') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true
      - uses: docker/setup-buildx-action@v2
      - name: Apk Cache
        uses: actions/cache@v3
        with:
          path: /tmp/var-cache-apk
          key: var-cache-apk-${{ hashFiles('Dockerfile') }}
      - name: Mount Apk Cache
        uses: reproducible-containers/buildkit-cache-dance@v2.1.2
        with:
          cache-source: /tmp/var-cache-apk
          cache-target: /var/cache/apk
      - name: Go Cache
        uses: actions/cache@v3
        with:
          path: /tmp/go-mod
          key: go-mod-${{ hashFiles('go.sum') }}
      - name: Mount Go Cache
        uses: reproducible-containers/buildkit-cache-dance@v2.1.2
        with:
          cache-source: /tmp/go-mod
          cache-target: /go/pkg/mod
      - name: Build ll-killer-go
        run: |
          docker buildx build --platform linux/arm64,linux/amd64 -f Dockerfile . -o /tmp/build --cache-from=type=gha --cache-to=type=gha,mode=max
          docker buildx build --platform linux/loong64 -f Dockerfile . -o /tmp/build --cache-from=type=gha --cache-to=type=gha,mode=max \
                              --build-arg XX_TRIPLE=loongarch64-alpine-linux-musl \
                              --build-arg XX_ALPINE_ARCH=loongarch64
          mv /tmp/build/linux_amd64/ll-killer ll-killer-amd64
          mv /tmp/build/linux_arm64/ll-killer ll-killer-arm64
          mv /tmp/build/ll-killer ll-killer-loong64
          sha1sum ll-killer-* >ll-killer.sha1sum

          XDASH='```'
          cat >> RELEASE.md <<EOF
          ## SHA1哈希值
          $XDASH
          $(cat ll-killer.sha1sum)
          $XDASH
          EOF
      - name: Verify
        run: |
          file ll-killer-*
      - name: Generate Changelog
        if: ${{ env.release == 'true' }}
        run: |
          go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest
          git-chglog -o RELEASE.md ${{github.ref_name}} || git-chglog --tag-filter-pattern '.*' -o RELEASE.md ${{github.ref_name}}
      - name: Release
        if: ${{ env.release == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ contains(github.ref_name,'dev') }}
          body_path: ./RELEASE.md
          files: |
            ./ll-killer-*
            ./ll-killer.sha1sum
